name: CI/CD/CD

on:
  push:
    branches:
      - main
        
#    paths:
#     - 'frontend/src/**'
#    - 'frontend/cypress/e2e/**'

permissions:
  contents: read 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run some placeholder tests
        run: |
          echo howdy

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: pnpm

      - name: build step
        run: |
          pnpm install
          pnpm run build:clippy

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: production-files
          path: ./apps/examples/ClipboardCollector/dist

      - name: After Upload
        run: |
          ls -R
          echo trying to see what is here After upload

            
          # THIS WORKS.
          # https://github.com/kdog3682/bkl/actions/runs/8887495213
          # shows the artifacts as zip file
          # files are definitely found here
          # path: ./dist
          # files are NOT FOUND here.


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Before Download LS
        run: |
          ls -R
          echo trying to see what is here

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      - name: After Download LS
        run: |
          ls -R
          echo trying to see what is here

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
