name: CI/CD/CD

on:
  push:
    branches:
      - main
        
#    paths:
#     - 'frontend/src/**'
#    - 'frontend/cypress/e2e/**'

permissions:
  contents: read 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run some placeholder tests
        run: |
          echo howdy

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: pnpm

      - name: build step
        run: |
          pnpm install
          pnpm run build:clippy

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./apps/examples/ClipboardCollector/dist
          # path: ./dist


  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./apps/examples/ClipboardCollector/dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
