name: CI/CD/CD

on:
  push:
    branches:
      - main
        
#    paths:
#     - 'frontend/src/**'
#     - 'apps/src/**'

permissions:
  contents: write
  deployments: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run some placeholder tests
        run: |
          echo howdy

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
          cache: pnpm

      - name: build step
        run: |
          pnpm install
          pnpm run build:clippy

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: github-pages
          path: ./apps/examples/ClipboardCollector/dist

  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
